"""
This type stub file was generated by pyright.
"""

from enum import Enum

"""Enumerations."""
class WktVersion(Enum):
    """
     .. versionadded:: 1.9.0

    Supported CRS WKT string versions.
    """
    WKT2_2015 = ...
    WKT2 = ...
    WKT2_2019 = ...
    WKT1_GDAL = ...
    WKT1 = ...
    WKT1_ESRI = ...


