name: Mypy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: |
        python3 -m pip install -r requirements-types.txt
    - name: mypy
      run: |
        mypy fiona tests